### ISSUE TITLE
shiny 通过筛选日期无法将X轴日期类型数据联动（win7）

### ISSUE THREAD

**Issue by wuqiangwang** [madlogos/recharts#10]
@madlogos 

`server.R
library(shiny)
library(shinydashboard)
library(DT)
library(recharts)
server <- function(input, output,session) {
normal_data <- reactive({
normal_data<-data.frame(date=c( "2017-05-03" ,"2017-05-04" ,"2017-05-05" ,"2017-05-06", "2017-05-07" ,"2017-05-08" ,"2017-05-09", "2017-05-10", "2017-05-11", "2017-05-12"),
gmv=c(624209 ,472624, 399328, 375413, 361946 ,539620, 445253, 514724 ,656519 ,484356),
paid=c(593060 ,442278, 362852, 349019 ,336858 ,506433, 414796 ,463171 ,595089, 443657)
)
normal_data<-subset(normal_data,date>=as.Date(input$daterange[1]) &date<=as.Date(input$daterange[2] ))
normal_data<-as.data.frame(normal_data)
normal_data
})

output$normal_data <-
renderDataTable({

  DT::datatable(normal_data(),rownames=F,extensions = 'FixedHeader',options = list(
    fixedHeader=TRUE,bSort = T,bAutoWidth = T,bProcessing = F,pageLength = 9,
    lengthMenu = list(c(9,-1),c('9','All')),
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Chinese.json')))
  
})
output$plot1 <-renderEChart({
normal_data<-normal_data()
p<- echart(
list(
title = list(text = 'GMV & PAID',subtext="GMV AND PAID SALES",x="center",y="top"),
tooltip = list(show=TRUE, trigger = 'axis',axisPointer=list(type="cross")),
legend = list(orient="horizontal",y='bottom',data = c('GMV','PAID'),selected=list('GMV'=TRUE,'PAID'=FALSE)),
xAxis = list(type = 'category',data =normal_data$date,axisLine=list(lineStyle=list(color='Black',width=1)),splitLine = list(show = FALSE)),
yAxis = list(list( type = 'value', splitLine = list(show = FALSE) ,position="left", axisLine=list(show=FALSE,lineStyle=list(color='Black',width=1)))),
series = list(list( type = 'line',name="GMV",data =normal_data$gmv,itemStyle = list(normal = list(color = 'DarkRed', label = list(show = TRUE)))),
list( type = 'line',name="PAID",data =normal_data$paid,itemStyle = list(normal = list(color = 'Black', label = list(show = TRUE))))
)
)
, width = 1000, height = 400)

print(p)

})

}

ui.R

library(shiny)
library(shinydashboard)
library(DT)
library(recharts)
ui <- dashboardPage(

header <- dashboardHeader(title="Just For Test",titleWidth = 250),
sidebar <- dashboardSidebar(
width=250,
sidebarMenu(
id = "tabs",
menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard"))
)
),

body <- dashboardBody(

tabItems(
tabItem("dashboard",
eChartOutput("plot1",width = "100%", height = "300px"),
fluidRow(dateRangeInput("daterange","Daterange Select：",start = as.Date('2017/5/3'),end=as.Date('2017/5/12'),min=as.Date('2017/5/3'),max=as.Date('2017/5/12'))),
fluidRow(dataTableOutput("normal_data"))

        )
)
))

`

**Comment by wuqiangwang** [comment]
`server.R
library(shiny)
library(shinydashboard)
library(DT)
library(recharts)
server <- function(input, output,session) {
  normal_data <- reactive({  
    normal_data<-data.frame(date=c( "2017-05-03" ,"2017-05-04" ,"2017-05-05" ,"2017-05-06", "2017-05-07" ,"2017-05-08" ,"2017-05-09", "2017-05-10", "2017-05-11", "2017-05-12"),
                            gmv=c(624209 ,472624, 399328, 375413, 361946 ,539620, 445253, 514724 ,656519 ,484356),
                            paid=c(593060 ,442278, 362852, 349019 ,336858 ,506433, 414796 ,463171 ,595089, 443657)
                            )
    normal_data<-subset(normal_data,date>=as.Date(input$daterange[1]) &date<=as.Date(input$daterange[2] ))
    normal_data<-as.data.frame(normal_data)
    normal_data
  })
  
  output$normal_data <-
    renderDataTable({
      
      DT::datatable(normal_data(),rownames=F,extensions = 'FixedHeader',options = list(
        fixedHeader=TRUE,bSort = T,bAutoWidth = T,bProcessing = F,pageLength = 9,
        lengthMenu = list(c(9,-1),c('9','All')),
        language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Chinese.json')))
      
    })

  output$plot1 <-renderEChart({
    normal_data<-normal_data()
   p<- echart(
      list(
        title = list(text = 'GMV & PAID',subtext="GMV AND PAID SALES",x="center",y="top"),
        tooltip = list(show=TRUE, trigger = 'axis',axisPointer=list(type="cross")),
        legend = list(orient="horizontal",y='bottom',data = c('GMV','PAID'),selected=list('GMV'=TRUE,'PAID'=FALSE)),
        xAxis = list(type = 'category',data =normal_data$date,axisLine=list(lineStyle=list(color='Black',width=1)),splitLine = list(show = FALSE)),
        yAxis = list(list( type = 'value', splitLine = list(show = FALSE) ,position="left", axisLine=list(show=FALSE,lineStyle=list(color='Black',width=1)))),
        series = list(list( type = 'line',name="GMV",data =normal_data$gmv,itemStyle = list(normal = list(color = 'DarkRed', label = list(show = TRUE)))),
                      list( type = 'line',name="PAID",data =normal_data$paid,itemStyle = list(normal = list(color = 'Black', label = list(show = TRUE))))
                      )
      )
    , width = 1000, height = 400)
   # print(p)
   })


}

ui.R

library(shiny)
library(shinydashboard)
library(DT)
library(recharts)
ui <- dashboardPage(

header <- dashboardHeader(title="Just For Test",titleWidth = 250),
sidebar <- dashboardSidebar(
  width=250,
  sidebarMenu(
    id = "tabs",
    menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard"))
             )
),

body <- dashboardBody(

  tabItems(
    tabItem("dashboard",
            eChartOutput("plot1",width = "100%", height = "300px"),
            fluidRow(dateRangeInput("daterange","Daterange Select：",start = as.Date('2017/5/3'),end=as.Date('2017/5/12'),min=as.Date('2017/5/3'),max=as.Date('2017/5/12'))),
            fluidRow(dataTableOutput("normal_data"))
 
            )
  )
  ))



`

**Comment by adpose** [comment]
用dateRangeInput 输入时间范围，在data.frame中选择
筛选日期变化时间大小，子集（sub.data.frame）变化是正确的，
但是在echartr 的图里面，日期在目前显示的基础上变小，显示出来的图像会变换范围，但是在当前显示的最小日期之后改变（日期变大）那么图只会刷新，不会变化显示结果，

选取范围的最大日期 变大/变小 都可以正常改变输出结果

**Comment by wikithink** [comment]
绘图的时候试试echartr函数呢

**Comment by madlogos** [comment]
发布了一个补丁，请重新install_github。相信下面就是你想要的。
```r
library(shinydashboard)
library(DT)
library(recharts)
shinyApp(
    ui = dashboardPage(
        header <- dashboardHeader(title="Just For Test", titleWidth = 250),
        sidebar <- dashboardSidebar(
            width=250,
            sidebarMenu(
                id = "tabs",
                menuItem("Dashboard", tabName = "dashboard", 
                         icon = icon("dashboard"))
            )
        ),
        body <- dashboardBody(
            tabItems(
                tabItem("dashboard",
                        eChartOutput("plot1", width = "100%", height = "300px"),
                        fluidRow(dateRangeInput(
                            "daterange","Daterange Select：",
                            start = as.Date('2017/5/3'),
                            end = as.Date('2017/5/12'),
                            min = as.Date('2017/5/3'),
                            max = as.Date('2017/5/12'))),
                        fluidRow(dataTableOutput("normal_data"))
                )
            )
        )),
    server = function(input, output) {
        normal_data <- reactive({
            normal_data<-data.frame(
                date=c("2017-05-03", "2017-05-04", "2017-05-05", "2017-05-06", 
                       "2017-05-07", "2017-05-08", "2017-05-09", "2017-05-10", 
                       "2017-05-11", "2017-05-12"),
                gmv=c(624209 ,472624, 399328, 375413, 361946 ,539620, 445253, 
                      514724 ,656519 ,484356),
                paid=c(593060 ,442278, 362852, 349019 ,336858 ,506433, 414796,
                       463171 ,595089, 443657)
            )
            normal_data <- subset(
                normal_data,date >= as.Date(input$daterange[1]) & 
                    date <= as.Date(input$daterange[2] ))
            normal_data <- as.data.frame(normal_data)
            normal_data
        })
        
        output$normal_data <-
            renderDataTable({
                DT::datatable(
                    normal_data(), rownames=F, extensions = 'FixedHeader',
                    options = list(
                        fixedHeader=TRUE, bSort = T, bAutoWidth = T,
                        bProcessing = F,pageLength = 9,
                        lengthMenu = list(c(9,-1), c('9','All')),
                        language = list(
                            url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Chinese.json')))
            })
        output$plot1 <-renderEChart({
            normal_data<-normal_data()
            plot_data <- reshape2::melt(normal_data, id.var="date")
            plot_data$variable <- toupper(plot_data$variable)
            p <- echartR(plot_data, 
                         x=date, y=value, series=variable, type="line",
                         width = 1000, height = 400) %>%
                setTheme('gray') %>%
                setToolbox(pos=3) %>%
                setTitle('GMV & PAID', subtitle="GMV AND PAID SALES", pos=12) %>%
                setTooltip(trigger = 'axis', axisPointer=list(type="cross")) %>%
                setLegend(pos=6, selected="GMV") %>%
                setXAxis(type = 'category', axisLine=list(
                    lineStyle=list(color='Black',width=1)),
                    splitLine = list(show = FALSE)) %>%
                setYAxis(type="value", splitLine = list(show = FALSE) ,
                         axisLine=list(show=FALSE, lineStyle=list(
                             color='Black', width=1))) %>%
                setSeries('GMV', itemStyle=list(
                    normal = list(color = 'DarkRed', label = list(show = TRUE)))) %>%
                setSeries('PAID', itemStyle=list(
                    normal = list(color = 'Black', label = list(show = TRUE))))
            p
        })
    }
)
```
