### ISSUE TITLE
这里的那个雷达图，可以自定义每个X轴的最大最小值吗？

### ISSUE THREAD

**Issue by bang411** [madlogos/recharts#11]
如题，做雷达图不应该先定义每个轴的最大最小值吗？不知道recharts能否做到？目前貌似在文档里没看到有相应接口

**Comment by bang411** [comment]
我见echarts里的雷达图是可以做到的，但是我对前端知识了解不多，不知道recharts 能不能做到？

**Comment by madlogos** [comment]
要用[`setPolar`](http://madlogos.github.io/recharts/Widget_02_Polar_cn.html#-en)来配置，最大最小值在indicator参数里设置。这一点我没强调，不过你看echarts2的文档就会发现，`polar`是一个独立的参数。
