### ISSUE TITLE
是否支持将生成的recharts图合并，或网格化排列？

### ISSUE THREAD

**Issue by ZJUguquan** [madlogos/recharts#12]
@madlogos ， Hi，

请教您一个问题。
如果我生成了多个recharts图，有没有办法将其合并到一个“框”里？比如我画了5个图，想把他们排列成3行2列（最后一个位置是空的）。这有点类似于`par(mfrow=c(3,2))`这种需求...

1，看到您在[文档中](http://madlogos.github.io/recharts/Basic_Plots_21_Pie_cn.html#-en)把多个图成功排列了，请问在rmarkdown中是如何实现的？
2，如果在shiny中的话，可以实现吗？场景类似于：有一个多项选择框，用户选择4个数据，shiny就会自动生成4张图，以2×2形式排列；如果选择6个数据，则自动生成6张图，以3×2形式排列...

期待您的回复，祝好~

**Comment by madlogos** [comment]
Echarts2不支持对直角坐标系grid分面，这个特性要在Echarts3才支持。
在shiny中，就很难实现一个控件操控四个图了。
md文档中很好办，就是画个表格的事情。
```
<table>
<tr>
<td>图1</td>
<td>图2</td>
<td>图3</td>
</tr>
<tr>
<td>图4</td>
<td>图5</td>
<td></td>
</tr>
</table>
```

**Comment by ZJUguquan** [comment]
@madlogos ，OK，3Q~！
