### ISSUE TITLE
shiny的输入变化后上一幅图输出的结果还在

### ISSUE THREAD

**Issue by ZJUguquan** [madlogos/recharts#13]
@madlogos ，Hi，

很抱歉我又来打扰您了。。。

昨天在shiny中用你的包画recharts图时，发现shiny输入变化后，上一幅图的输出的结果还在，代码如下：
```r
library(recharts)
library(shiny)
shinyApp(
  ui = fluidPage(
    numericInput('n','n',10,10,500),
    eChartOutput('myChart')),
   server = function(input, output) {
     output$myChart = renderEChart({
       echartR(data.frame(x = rnorm(input$n), y = rnorm(input$n)), x, y)})
   }
)
```
原先是10个点，
![1](https://user-images.githubusercontent.com/19544736/29595713-db0643ba-87eb-11e7-9753-3bc416a1f6a4.png)
增加至500个点，
![2](https://user-images.githubusercontent.com/19544736/29595740-013f1c14-87ec-11e7-990b-a3384c93f521.png)
再变成20个点时，前面的500个点还在。。。。。
![3](https://user-images.githubusercontent.com/19544736/29595768-1e34cd0a-87ec-11e7-8789-6af0fe6c032a.png)

**Comment by madlogos** [comment]
不确定修补思路会不会引发新问题。现在的办法是每次renderValue，渲染画布之前强行清空实例。
发了个补丁，重新install_github后试试。
