### ISSUE TITLE
安装失败 there is no package called ‘curl’

### ISSUE THREAD

**Issue by kk0spence** [madlogos/recharts#17]
if (!require(devtools)) library(devtools)
> install_github("madlogos/recharts")
Installation failed: there is no package called ‘curl’

新手小白请问这是什么原因

**Comment by madlogos** [comment]
没有装对应的包。`install.packages("curl")`.

**Comment by kk0spence** [comment]
谢谢回复，安转了packages后，又出现了点问题
> if (!require(devtools)) library(devtools)
> install_github("madlogos/recharts")
Installation failed: error setting certificate verify locations:
  CAfile: 
  CApath: none

请问这是什么原因

**Comment by madlogos** [comment]
试试装个`RCurl`或`httr`包。如果还不行，用搜索引擎多找几个答案。新手遇到的问题一般很多人都不同程度遇到过。
<https://github.com/ramnathv/rCharts/issues/135#issuecomment-20140615>

**Comment by kk0spence** [comment]
浏览过这个帖子，安装了httr包后成功了，非常感谢^ ^
