### ISSUE TITLE
你好，关于recharts安装问题请教一下

### ISSUE THREAD

**Issue by CoonRu** [madlogos/recharts#18]
我新下载的R3.4.3和新的rstudio之后，在rstudio里面安装了devtools，再执行了
if (!require(devtools)) library(devtools)
devtools::install_github('madlogos/recharts')
命令后报了这样的错误
![image](https://user-images.githubusercontent.com/30849529/33696832-09c7579c-db3f-11e7-8fd2-c458c8f64b6e.png)
请问怎么解决呢。
我试过直接在主页上download了recharts，用rstudio打开后再build里安装也是同样的错误。

**Comment by CoonRu** [comment]
install.packages("RColorBrewer")
install.packages("ggthemes")
install.packages("data.table")
install.packages("knitr")
反复执行安装查缺包解决了但是
rstudio有没有能帮我安装我缺少的包的功能呢？而不是只告诉我 no package

**Comment by madlogos** [comment]
下次我会把这几个包放到DESCRIPTION的imports里。
