### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by land23** [madlogos/recharts#2]
安装的时候出现这样的问题
Downloading GitHub repo madlogos/recharts@master
from URL https://api.github.com/repos/madlogos/recharts/zipball/master
Installing recharts
"d:/Program Files/R/R-3.3.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/aresren/AppData/Local/Temp/RtmpINoq5T/devtools33c28f3c29/madlogos-recharts-ab0bdfc"  \
  --library="d:/Program Files/R/R-3.3.2/library" --install-tests 

'd:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Error: Command failed (1)

**Comment by madlogos** [comment]
[参考此贴](http://f.dataguru.cn/forum.php?mod=viewthread&tid=486119&page=1#pid1438505)
R和Rstudio都不要装在含空格的路径下。

**Comment by land23** [comment]
感谢，已经解决，期待版主的持续更新
