### ISSUE TITLE
无法和data.table一起使用

### ISSUE THREAD

**Issue by swefn** [madlogos/recharts#20]
同样的数据，保存为xlsx后用xlsx包读取后绘图完全没有问题，但是数据量大的情况下xlsx就有些慢了，于是改用data.table包，但是用fread读取数据后，无法画图，报错内容是：

Error in `[.data.table`(data, , j) : 
  j (the 2nd argument inside [...]) is a single symbol but column name 'j' is not found. Perhaps you intended DT[,..j] or DT[,j,with=FALSE]. This difference to data.frame is deliberate and explained in FAQ 1.1.

请问如何解决？

**Comment by madlogos** [comment]
fread读取后，用`as.data.frame`转为数据帧，再使用此包。data.table的列引用方法和data.frame有所不同，没有做兼容。
