### ISSUE TITLE
为什么安装了这个包,案例里的函数不能用啊?

### ISSUE THREAD

**Issue by coreanachina** [madlogos/recharts#22]
> library("recharts", lib.loc="~/R/win-library/3.4")
> echartr(iris, Sepal.Length, Sepal.Width, series = Species)
Error in echartr(iris, Sepal.Length, Sepal.Width, series = Species) : 
  could not find function "echartr"

**Comment by madlogos** [comment]
你是怎么装这个包的？有很多包都叫recharts。

**Comment by coreanachina** [comment]
从“Code”那里下载的recharts-master.zip，然后在rstudio里点packages，install from 选择package Archive File安装。

**Comment by madlogos** [comment]
你从github下载的是源代码，没有经过R CMD build编译，根本不是package archive file。仔细阅读文档，先装`devtools`包，然后`install_github('madlogos/recharts')`。

**Comment by coreanachina** [comment]
> install_github('madlogos/recharts')
Downloading GitHub repo madlogos/recharts@master
from URL https://api.github.com/repos/madlogos/recharts/zipball/master
Installing recharts
"d:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/user/AppData/Local/Temp/RtmpAR4Bv1/devtools22fc5ce15eef/madlogos-recharts-39cc88c"  \
  --library="D:/Users/user/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'recharts' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'ggthemes'
ERROR: lazy loading failed for package 'recharts'
* removing 'D:/Users/user/Documents/R/win-library/3.4/recharts'
Installation failed: Command failed (1)
需要先安装ggthemes包，才可以安装这个包。建议您在安装说明里说明这个问题，不然很多没有安装ggthems包的人会安装失败。
