### ISSUE TITLE
用recharts做出的中国地图的热点图，彩晕超出国界，怎样将彩晕控制国界内

### ISSUE THREAD

**Issue by qinuse** [madlogos/recharts#24]
echartr(mydata_count_prov, NAME, 病例数, type="map_china") %>% addHeatmap(data=mydata_count_town[,2:4], blurSize = 20, minAlpha=0.035,opacity=0.8) %>%
  setTitle("") %>%
  setTheme('dark')

**Comment by madlogos** [comment]
echarts文档里没有相应的选项，应该是做不到的。
