### ISSUE TITLE
在Rmd文件中使用报错

### ISSUE THREAD

**Issue by xwydq** [madlogos/recharts#25]
如下的Rmd:
```
---
title: "Untitled"
output: html_document
---
```{r}
library(recharts)
echart(iris, ~ Sepal.Length, ~ Sepal.Width)
```
报错：
`
pandoc: Could not fetch ～/R/x86_64-redhat-linux-gnu-library/3.4/recharts/htmlwidgets/lib/echarts/scatter.js
～/R/x86_64-redhat-linux-gnu-library/3.4/recharts/htmlwidgets/lib/echarts/scatter.js: openBinaryFile: does not exist (No such file or directory)
错误: pandoc document conversion failed with error 67
停止执行
`
为什么要去找scatter.js这个文件，
PS直接在R中运行时正常的

**Comment by madlogos** [comment]
因为你用的是`echart`函数。这个包是从yihui那里fork来的，所以我保留了他的核心函数，但是没有做进一步兼容。我这个版本的核心函数叫`echartR`。你不妨仔细看一下文档。
