### ISSUE TITLE
How to use recharts make static image?

### ISSUE THREAD

**Issue by slsongge** [madlogos/recharts#28]

**Comment by slsongge** [comment]
I want use recharts to make static images, because i need to save lots of images. Thanks!

**Comment by madlogos** [comment]
recharts is built on top of `htmlwidgets`, so you can save the recharts object to a .html file, then convert it to image using `webshot`. You can refer to <https://stackoverflow.com/questions/45298144/convert-html-output-to-image>.
By now, Echarts2 does not support a better way to export the static image. Echarts4 has a `echartInstance.getDataUrl` method, which is a good solution. But not supported here.
