### ISSUE TITLE
'width_sum_.'变量缺失

### ISSUE THREAD

**Issue by land23** [madlogos/recharts#3]
按照用例出现如下问题
 echartr(iris, x=Sepal.Width, y=Petal.Width)
Error in eval(expr, envir, enclos) : object 'width_sum_.' not found

**Comment by madlogos** [comment]
是因为data.table更新后修改了dcast算法，中间产出物的命名变了。已经更新0.1-1，请重新build。目前直角坐标系以外的图（pie, funnel, radar, map）都有问题，因为在重写facet语法。shiny也有问题。等0.2版再修复。
