### ISSUE TITLE
echarts产生的图怎么在shiny中展现？

### ISSUE THREAD

**Issue by joowade** [madlogos/recharts#4]
楼主您好，我想使用echarts在shiny中做数据展现。可是直接在server.R中写如下：
output$myplot <- renderPlot({
    echartr(iris, Sepal.Length, Sepal.Width, series = Species)
  })
在ui.R中写如下：
mainPanel(
plotOutput('myplot')
)
页面上是空白。请问有没有可以提供的example？万分感谢！！！
另，建议您在echarts的教程中添加相关shiny的例子

**Comment by madlogos** [comment]
shiny目前支持得很不好，因为我对shiny不熟悉。为了自动适配宽度，我引入了elementId，每次修改就自动随机化一次。但是这个参数shiny不接受，所以就不断bug。需要重新设计。

目前打了个小补丁到v 0.1-2。勉强可以写app，但会有警报。你试一下这个例子（见eChartOutput函数的帮助）。
```r
shinyApp(
    ui = fluidPage(eChartOutput('myChart', height='500px')),
    server = function(input, output) {
        chart = echartr(data.frame(x = rnorm(100), y = rnorm(100)), x, y)
        output$myChart = renderEChart(chart)
    }
)
```
