### ISSUE TITLE
您好，请问仪表盘(gauge)能否自定义刻度线/分割点？

### ISSUE THREAD

**Issue by ZJUguquan** [madlogos/recharts#5]
Yiying Wang，您好，

非常感谢您在recharts包的开发上做出的贡献，这个包让R用户仅使用dataframe就能够轻松画出各种echarts图，真的非常赞！！

这里想请教您一个问题，在使用echartr函数画仪表盘图(gauge)时，代码会自动将20%和80%的临界值设为分割点，并用不同的颜色表示0到20%，20%到80%，80%到100%三个区间的值。那么请问能否自定义分割点呢，比如，我想设为50%和80%（或者甚至更多的分割点）？

我记得之前看到过一篇文章“Function echartR with package recharts”（这篇文章的作者应该也是您吧），里面使用echartR函数绘制gauge图时，是可以自己定义分割点的。在您新开发的这个版本上，貌似这个功能没有了。。。

希望您能够回复我的疑问，感谢！
2017祝好~

**Comment by madlogos** [comment]
你好。gauge图没有写更多封装函数，所以自定义属性目前需要通过`setSeries`传入。请参考[setSeries仪表盘](https://madlogos.github.io/recharts/setSeries_cn.html#229_仪表盘gauge)，主要通过min, max, splitNumber几个参数来控制。

**Comment by ZJUguquan** [comment]
@madlogos 感谢！

我仔细对照了<a href="https://madlogos.github.io/recharts/setSeries_cn.html#229_%E4%BB%AA%E8%A1%A8%E7%9B%98gauge">setSeries仪表盘</a>的参数和<a href="http://echarts.baidu.com/echarts2/doc/doc.html#SeriesGauge">百度echarts2官方文档</a>的参数，发现用axisLine参数可以控制分割点。

```r
#原图
data = data.frame(x='KR/min', y=6.3)
p = echartr(data, x, y, type='gauge')
p
```
![20170104101414](https://cloud.githubusercontent.com/assets/19544736/21630350/3a2ff674-d26b-11e6-8c22-6e91396f4156.png)

```r
#更改axisLine参数后
p %>% setSeries(axisLine=list(show=TRUE, 
                          lineStyle=list(color=list(list(0.5, '#2ec7c9'), 
                                                    list(0.8, '#b6a2de'), 
                                                    list(1, '#5ab1ef')), width=5)))
```
![20170104101344](https://cloud.githubusercontent.com/assets/19544736/21629892/2bc0a11e-d267-11e6-8b41-46565e0b00d2.png)

再次感叹recharts包的强大之处！
