### ISSUE TITLE
timeslots在addHeatmap中无效

### ISSUE THREAD

**Issue by leoyyang** [madlogos/recharts#6]
目标是希望在china_map中记入heatmap的时间序列变化
`
echartr(data = pm25.gps.monthly, lng = lng, lat = lat, y = PM2.5平均值, t = 时间, type = c("china_map"))  %>%
  addHeatmap(data = pm25.gps.monthly,
             t = 时间,
             mode = "overide")
`
运行报错，找不到`时间`这个变量。 去掉t参数，数据会被加总到一起，而不是分时间展现。

**Comment by madlogos** [comment]
`timeslots`不能这样用。timeslots只能是具体的文本或数值向量，对应echartr中初始化的时间轴变量t的不同水平，告诉recharts把addHeatmap中的数据插入到具体哪个时间切片里。所以应该
```r
echartr(data = pm25.gps.monthly, lng = lng, lat = lat, y = PM2.5平均值, 
            t = 时间, type = c("china_map")) %>% 
addHeatmap(data = pm25.gps.monthly[pm25.gps.monthly$时间 == 1,], t = 1) %>% 
overideHeatmap(...) %>% ...
``` 
这样的形式，一个切片一个切片地加。比较笨拙，主要是一开始设计时没考虑得太细。

不过经我实际测试，ECharts2并不支持map中的heatmap随时间轴变化。所以只能等我抽出时间来完成开发recharts2了（目前完全搁置），希望ECharts3里面不存在这个问题。

这个[issue](https://github.com/ecomfe/echarts/issues/5141)我已经提到百度官方，但基本不指望ECharts2修复它了。

**Comment by leoyyang** [comment]
好，我暂时用个循环不断overideHeatmap吧，感谢，希望这个bug尽快修复。带Map的heatmap其实还是比较常用的。

**Comment by madlogos** [comment]
官方的回复是
`推荐用 echarts3 中的 heatmap`
所以只能等有时间再开发recharts2。
