### ISSUE TITLE
Shiny中设置数据集筛选框改变recharts图，筛选框选项为中文内容时，筛选无效

### ISSUE THREAD

**Issue by XuXin09** [madlogos/recharts#7]
Yiying Wang，
         您好，谢谢您对recharts包的开发。
         目前用于shiny时，发现了如题目所述的问题。
`selectInput("dataset", "选择:",  choices = c("A","B“,“C”,"D"))` choices选项为英文和数字都可以顺利跑出，
而
`selectInput("dataset", "选择:",  choices = c("名字A","名字B“,“名字C”,"名字D"))`时，选项无法与图形联动。

请教您原因和解决办法，谢谢您！

**Comment by madlogos** [comment]
应该是编码Encoding的问题。我在Linux下是OK的。你是在Windows下？
```
if (interactive()) {
    shinyApp(
        ui = fluidPage(
              selectInput("grouping", "选择:", choices = c("上", "下", "左", "右")),
              eChartOutput('myChart')),
        server = function(input, output) {
            dt = data.frame(
               x = rnorm(100), y = rnorm(100), g=rep(c("上", "下", "左", "右"), 25), 
               stringsAsFactors=FALSE)
            output$myChart = renderEChart({
                echartr(dt[dt$g == input$grouping, ], x, y, series=g)
            })
        }
    )
}
```

**Comment by XuXin09** [comment]
您好，谢谢回复。是的，是在window下。
请问编码需要如何调整呢？

**Comment by madlogos** [comment]
我在Windows7下用上述代码运行，也是成功的。确保R脚本以UTF-8编码保存，看能不能正常运行。

**Comment by madlogos** [comment]
也可以参考[这个](https://github.com/yihui/knitr/issues/1395)。CRAN发行版的htmltools可能有bug，试试install_github("rstudio/htmltools")。
