### ISSUE TITLE
recharts 热力图可以自定义某个图片吗？

### ISSUE THREAD

**Issue by bang411** [madlogos/recharts#8]
如题所述，我想做一个网站页面热力图，想自定义热力图的图片

**Comment by madlogos** [comment]
目前是不行的。由于htmlwidgets最终将数据封装为json，所以如果要垫一张自定义图片，需要把它转成base64，然后手动去改html。

**Comment by madlogos** [comment]
我找遍了整个echarts2的配置手册，没有查到背景图片这个东西。可能就是不支持。

**Comment by bang411** [comment]
感谢
