### ISSUE TITLE
热力图可以显示到城市级别吗

### ISSUE THREAD

**Issue by RemmyGuo** [madlogos/recharts#9]
Yiying Wang，您好！
       这个包是用过的对echarts封装最顺畅的一个，谢谢您的开发~
       目前想画一个中国城市级别的热力图，仔细找了但是没有找到，不知道目前的这个版本有没有这个功能？望指教~

**Comment by madlogos** [comment]
你好。目前并不支持全局城市级显示。如果要支持，可能需要整个重写china.js。我对R比较熟悉，js就不是很懂了。
